export const CREATE_CLAIM = "CREATE_CLAIM";
export const CREATE_POLICY = "CREATE_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const LOGIN_IN_PROGRESS = "LOGIN_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
